import "./globals.css";
import "./reset.css";

import { MousePositionListener } from "@/modules/mouse-position/listener";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MousePositionListener />
        {children}
      </body>
    </html>
  );
}
